services:
  - type: web
    name: nufl-football-league-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && chmod +x start.sh && ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production 